---
title: "vittorio_simulations"
author: "vittorio"
date: "2/8/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, warnings=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message = FALSE, error=FALSE)
source("AB_MIPs.R")
library(ggplot2)
library(reshape2)
library(dbarts)
library(RColorBrewer)
require(dbarts)
require(MatchIt)
require(beepr)
require(cem)
require(tidyverse)
source("sims.R")
```

```{r}
X_dgp = function(n, p){
  matrix(runif(n * p, min = -5, max = 5), n, p)
}

e_dgp <- function(X) {
  expit(.3, X)
} 
```


2D: Constant 
```{r}
y_dgp <- function(x, z, eps) {
  beta_tilde <- 5
  Y <- 
    beta_tilde * z + eps
  return(Y)
}
# res <- matching_sim(10, 200, 2, X_dgp = X_dgp, y_dgp = y_dgp, e_dgp = e_dgp,
#                    estimators =  c('MIQP-Fhat', 'Greedy', 'Nearest Neighbor', 
#                                    'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))
# 
# res$estimator %<>% factor(levels = c('MIQP-Fhat', 'Greedy', 'Nearest Neighbor', 
#                                      'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))

res <- matching_sim(10, 200, 2, X_dgp = X_dgp, y_dgp = y_dgp, e_dgp = e_dgp,
                   estimators =  c('Greedy', 'Nearest Neighbor', 
                                   'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))

res$estimator %<>% factor(levels = c('Greedy', 'Nearest Neighbor', 
                                     'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))

saveRDS(res, 'conf_sim_constant.rds')
CATE_error_plot(res)
ggsave(paste('conf_sim_constant.png'), 
       width = 10, height = 8, units = 'in', device = 'png', dpi = 300)
```

2D: Open box in 1D
```{r}
y_dgp <- function(x, z, eps) {
  beta_tilde <- 5
  Y <- 
    beta_tilde * (x[, 1] < 1.5) * z + eps
  return(Y)
}
res <- matching_sim(10, 200, 2, X_dgp = X_dgp, y_dgp = y_dgp, e_dgp = e_dgp,
                   estimators =  c('MIQP-Fhat', 'Greedy', 'Nearest Neighbor', 
                                   'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))

res$estimator %<>% factor(levels = c('MIQP-Fhat', 'Greedy', 'Nearest Neighbor', 
                                     'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))
saveRDS(res, 'conf_sim_open_box_1d.rds')
CATE_error_plot(res)
ggsave(paste('conf_sim_open_box_1d.png'), 
       width = 10, height = 8, units = 'in', device = 'png', dpi = 300)
```

2D: Box in 1D
```{r}
y_dgp <- function(x, z, eps) {
  beta_tilde <- 5
  Y <- 
    beta_tilde * (x[, 1] > 1 & x[, 1] < 2.5) * z + eps
  return(Y)
}
out <- matching_sim(1, 200, 2, X_dgp = X_dgp, y_dgp = y_dgp, e_dgp = e_dgp,
                   estimators =  c('MIQP-Fhat', 'Greedy', 'Nearest Neighbor',
                                   'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))

res <- out[['CATEs']]
res$estimator %<>% factor(levels = c('MIQP-Fhat', 'Greedy', 'Nearest Neighbor',
                                     'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))

out <- matching_sim(1, 200, 2, X_dgp = X_dgp, y_dgp = y_dgp, e_dgp = e_dgp,
                   estimators =  c('Greedy', 'Nearest Neighbor', 
                                   'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))

res <- out[['CATEs']]
res$estimator %<>% factor(levels = c('Greedy', 'Nearest Neighbor', 
                                     'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))
saveRDS(res, 'conf_sim_box_1d.rds')
# CATE_error_plot(res)

bin_plot(out$bins[[1]][['MIQP-Fhat']], out$test_df[[1]], 1, 2, 1, 2.5, -5, 5)

# ggsave(paste('conf_sim_box_1d.png'), 
#        width = 10, height = 8, units = 'in', device = 'png', dpi = 300)
```

2D: Open box in 2D
```{r}
y_dgp <- function(x, z, eps) {
  beta_tilde <- 5
  Y <- 
    beta_tilde * (x[, 1] < 1.5 & x[, 2] < 1.5) * z + eps
  return(Y)
}
res <- matching_sim(10, 200, 2, X_dgp = X_dgp, y_dgp = y_dgp, e_dgp = e_dgp,
                   estimators =  c('MIQP-Fhat', 'Greedy', 'Nearest Neighbor', 
                                   'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))

res$estimator %<>% factor(levels = c('MIQP-Fhat', 'Greedy', 'Nearest Neighbor', 
                                     'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))
saveRDS(res, 'conf_sim_open_box_2d.rds')
CATE_error_plot(res)
ggsave(paste('conf_sim_open_box_2d.png'), 
       width = 10, height = 8, units = 'in', device = 'png', dpi = 300)
```

2D: Box in 2D
```{r}
y_dgp <- function(x, z, eps) {
  beta_tilde <- 5
  Y <- 
    beta_tilde * (x[, 1] > 1 & x[, 1] < 2 & x[, 2] > 3 & x[, 2] < 4) * z + eps
  return(Y)
}
res <- matching_sim(10, 200, 2, X_dgp = X_dgp, y_dgp = y_dgp, e_dgp = e_dgp,
                   estimators =  c('MIQP-Fhat', 'Greedy', 'Nearest Neighbor', 
                                   'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))

res$estimator %<>% factor(levels = c('MIQP-Fhat', 'Greedy', 'Nearest Neighbor', 
                                     'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))
saveRDS(res, 'conf_sim_box_2d.rds')
CATE_error_plot(res)
ggsave(paste('conf_sim_box_2d.png'), 
       width = 10, height = 8, units = 'in', device = 'png', dpi = 300)
```

2D: Union of 1D boxes 
```{r}
y_dgp <- function(x, z, eps) {
  beta_tilde <- 5
  Y <- 
    beta_tilde * ((x[, 1] > 1 & x[, 1] < 2) | (x[, 1] > 3.75 & x[, 1] < 4.5)) * z + eps
  return(Y)
}
res <- matching_sim(10, 200, 2, X_dgp = X_dgp, y_dgp = y_dgp, e_dgp = e_dgp,
                   estimators =  c('MIQP-Fhat', 'Greedy', 'Nearest Neighbor', 
                                   'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))

res$estimator %<>% factor(levels = c('MIQP-Fhat', 'Greedy', 'Nearest Neighbor', 
                                     'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))
saveRDS(res, 'conf_sim_union_box_1d.rds')
CATE_error_plot(res)
ggsave(paste('conf_sim_union_box_1d.png'), 
       width = 10, height = 8, units = 'in', device = 'png', dpi = 300)
```

2D: Union of 2D boxes 
```{r}
y_dgp <- function(x, z, eps) {
  beta_tilde <- 5
  Y <- 
    beta_tilde * ((x[, 1] > 1 & x[, 1] < 2 & x[, 2] > 1 & x[, 2] < 2) | 
                    (x[, 1] > 3.75 & x[, 1] < 4.5 & x[, 2] > 3 & x[, 2] < 4)) * z + eps
  return(Y)
}
res <- matching_sim(10, 200, 2, X_dgp = X_dgp, y_dgp = y_dgp, e_dgp = e_dgp,
                   estimators =  c('MIQP-Fhat', 'Greedy', 'Nearest Neighbor', 
                                   'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))

res$estimator %<>% factor(levels = c('MIQP-Fhat', 'Greedy', 'Nearest Neighbor', 
                                     'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))
saveRDS(res, 'conf_sim_union_box_2d.rds')
CATE_error_plot(res)
ggsave(paste('conf_sim_union_box_2d.png'), 
       width = 10, height = 8, units = 'in', device = 'png', dpi = 300)
```

2D: Linear in 1D
```{r}
y_dgp <- function(x, z, eps) {
  beta_tilde <- 5
  Y <- 
    beta_tilde * x[, 1] * z + eps
  return(Y)
}
res <- matching_sim(10, 200, 2, X_dgp = X_dgp, y_dgp = y_dgp, e_dgp = e_dgp,
                   estimators =  c('MIQP-Fhat', 'Greedy', 'Nearest Neighbor', 
                                   'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))

res$estimator %<>% factor(levels = c('MIQP-Fhat', 'Greedy', 'Nearest Neighbor', 
                                     'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))
saveRDS(res, 'conf_sim_linear_1d.rds')
CATE_error_plot(res)
ggsave(paste('conf_sim_linear_1d.png'), 
       width = 10, height = 8, units = 'in', device = 'png', dpi = 300)
```

2D: Linear in 2D
```{r}
y_dgp <- function(x, z, eps) {
  beta_tilde <- 5
  Y <- 
    beta_tilde * (x[, 1] + x[, 2] / 3) * z + eps
  return(Y)
}
res <- matching_sim(10, 200, 2, X_dgp = X_dgp, y_dgp = y_dgp, e_dgp = e_dgp,
                   estimators =  c('MIQP-Fhat', 'Greedy', 'Nearest Neighbor', 
                                   'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))

res$estimator %<>% factor(levels = c('MIQP-Fhat', 'Greedy', 'Nearest Neighbor', 
                                     'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))
saveRDS(res, 'conf_sim_linear_2d.rds')
CATE_error_plot(res)
ggsave(paste('conf_sim_linear_2d.png'), 
       width = 10, height = 8, units = 'in', device = 'png', dpi = 300)
```

2D: Quadratic in 1D
```{r}
y_dgp <- function(x, z, eps) {
  beta_tilde <- 2
  Y <- 
    beta_tilde * (x[, 1] - 2.5) ^ 2 * z + eps
  return(Y)
}
res <- matching_sim(10, 200, 2, X_dgp = X_dgp, y_dgp = y_dgp, e_dgp = e_dgp,
                   estimators =  c('Greedy', 'Nearest Neighbor', 
                                   'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))

res$estimator %<>% factor(levels = c('Greedy', 'Nearest Neighbor', 
                                     'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))
saveRDS(res, 'conf_sim_quad_1d.rds')
CATE_error_plot(res)
ggsave(paste('conf_sim_quad_qd.png'), 
       width = 10, height = 8, units = 'in', device = 'png', dpi = 300)
```

2D: Quadratic in 2D
```{r}
y_dgp <- function(x, z, eps) {
  beta_tilde <- 2
  Y <- 
    beta_tilde * ((x[, 1] - 2.5) ^ 2 + (x[, 2] - 4) ^ 2) * z + eps
  return(Y)
}
res <- matching_sim(10, 200, 2, X_dgp = X_dgp, y_dgp = y_dgp, e_dgp = e_dgp,
                   estimators =  c('MIQP-Fhat', 'Greedy', 'Nearest Neighbor', 
                                   'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))

res$estimator %<>% factor(levels = c('MIQP-Fhat', 'Greedy', 'Nearest Neighbor', 
                                     'CEM', 'Full Matching', 'Prognostic', 'Mahalanobis'))
saveRDS(res, 'conf_sim_quad_2d.rds')
CATE_error_plot(res)
ggsave(paste('conf_sim_quad_2d.png'), 
       width = 10, height = 8, units = 'in', device = 'png', dpi = 300)
```

Load Data
```{r}
require(stringr)
require(xtable)
path <- './simresults/data/'
files <- list.files(path)
n_sim_types <- sum(sapply(files, function(file) str_detect(file, 'conf')))
sim_results <- data.frame(actual = NULL, predicted = NULL, estimator = NULL)
CATEs_per_sim_type <- NULL
for (file in files) {
  if (str_detect(file, 'conf')) {
    tmp <- readRDS(paste0(path, file))
    sim_results %<>% rbind(tmp)
    CATEs_per_sim_type %<>% c(nrow(tmp))
  }
}

sims_per_type <- 10
n_estimators <- 7

sim_types <- c('Closed Box 1D', 'Closed Box 2D', 'Constant',
              'Linear 1D', 'Linear 2D', 'Open Box 1D', 'Open Box 2D',
              'Quadratic 1D', 'Quadratic 2D', 'Union of Boxes 1D', 'Union of Boxes 2D')

sim_results %<>% 
  mutate(sim_type = rep(sim_types, CATEs_per_sim_type),
         error = abs(actual - predicted)) %>%
  group_by(sim_type, estimator) %>%
  summarize(avg_error = mean(error, na.rm = TRUE),
            sd_error = sd(error, na.rm = TRUE),
            avg_sd = paste0(as.character(round(avg_error, 2)), ' (', 
                            as.character(round(sd_error, 2)), ')')) %>%
  dplyr::select(-c(avg_error, sd_error)) %>%
  dcast(sim_type ~ estimator) 

print(xtable(sim_results), include.rownames = FALSE)

```

